services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.4
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"      # internal listener (containers use kafka:9092)
      - "29092:29092"    # host listener (host uses localhost:29092)
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    depends_on:
      - kafka
    ports:
      - "8080:8080"   # Spark master UI
      - "7077:7077"   # Spark master RPC
    volumes:
      - ./spark:/opt/spark/work-dir
    command: ["/bin/bash", "-lc", "/opt/spark/sbin/start-master.sh -h spark-master; tail -f /opt/spark/logs/*master*.out"]

  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"   # Spark worker UI
    volumes:
      - ./spark:/opt/spark/work-dir
    command: ["/bin/bash", "-lc", "/opt/spark/sbin/start-worker.sh spark://spark-master:7077; tail -f /opt/spark/logs/*worker*.out"]